name: Deploy to Oracle Server

on:
  push:
    branches:
      - main  # Runs only when pushing to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ✅ Build the Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/actions:latest .

      # ✅ Push Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/actions:latest

      # ✅ Deploy to Oracle Server via SSH
      - name: Deploy to Oracle Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Ensure Docker is running
            sudo systemctl start docker || true

            # Stop and remove old container
            sudo docker stop actions-container || true
            sudo docker rm actions-container || true

            # Pull the latest image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/actions:latest

            # Run the new container
            sudo docker run -d --name actions-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/actions:latest
