name: Docker Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-website .

      - name: Run Docker container
        run: |
          docker run -d --name my-website-container -p 8080:80 my-website
          echo "Website is running on port 8080"

      - name: Test website
        run: |
          sleep 5 # Wait for the container to start
          curl http://localhost:8080
